{
  "formatVersion": "1.1",
  "component": {
    "group": "org.junit.platform",
    "module": "junit-platform-engine",
    "version": "1.6.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "6z5e52fxwrbhlhwdrxkyhcdiiu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.junit",
          "module": "junit-bom",
          "version": {
            "requires": "5.6.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.apiguardian",
          "module": "apiguardian-api",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.opentest4j",
          "module": "opentest4j",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-commons",
          "version": {
            "requires": "1.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "junit-platform-engine-1.6.2.jar",
          "url": "junit-platform-engine-1.6.2.jar",
          "size": 174108,
          "sha512": "9cd0926e5525c478692950fef24075641a57ba09c0a9f57d25a1c27ba4f9a5b5541574f90e8fcfb877b3bad676f4a17d0c4080cf8ef7efec9db1f67ede3694dd",
          "sha256": "23b41ac95e4673f7b31e8502424451be4154fe4db1d448448945e2215473c246",
          "sha1": "1752cad2579e20c2b224602fe846fc660fb35805",
          "md5": "b41ff34208cb373de0bf954e70c4d78b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.junit",
          "module": "junit-bom",
          "version": {
            "requires": "5.6.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.apiguardian",
          "module": "apiguardian-api",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.opentest4j",
          "module": "opentest4j",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-commons",
          "version": {
            "requires": "1.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "junit-platform-engine-1.6.2.jar",
          "url": "junit-platform-engine-1.6.2.jar",
          "size": 174108,
          "sha512": "9cd0926e5525c478692950fef24075641a57ba09c0a9f57d25a1c27ba4f9a5b5541574f90e8fcfb877b3bad676f4a17d0c4080cf8ef7efec9db1f67ede3694dd",
          "sha256": "23b41ac95e4673f7b31e8502424451be4154fe4db1d448448945e2215473c246",
          "sha1": "1752cad2579e20c2b224602fe846fc660fb35805",
          "md5": "b41ff34208cb373de0bf954e70c4d78b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "junit-platform-engine-1.6.2-javadoc.jar",
          "url": "junit-platform-engine-1.6.2-javadoc.jar",
          "size": 943558,
          "sha512": "20d052f069db1aa7ee5bea2e40573797709c2f0cfe78b17a42ff1a6bfc6f83508a8c6535ca9f1f99821eea2d142f89c9e66eb0a4a9205d7eef963adaa5e04e87",
          "sha256": "91d53c574433c00411fcfa77a0e919ee5b206301f44ac0263253f426efe60273",
          "sha1": "3c3791e81a7c73fbf2345b0b9b16cd56ff979628",
          "md5": "e0ffa6a413653401261d5b26c8e095c9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "junit-platform-engine-1.6.2-sources.jar",
          "url": "junit-platform-engine-1.6.2-sources.jar",
          "size": 127678,
          "sha512": "c98e5fd839feb486325867b5a740c11842856f20b97259b9635c4359f3b86299cb7b73926443b06d6eeee9b69f4fc0c63e9231f546a822db2a60f0bc1b30ec38",
          "sha256": "4f013f0ad0dd795f5072d563e2256a44608f562e9bed3fbfd1d9faa3c92d5fdb",
          "sha1": "9240cb4f3ee7693f8f18f4140acc7f8c83336e30",
          "md5": "5c00a274aa6b3cfe7f5f33f6c3fdc406"
        }
      ]
    }
  ]
}
