{
  "formatVersion": "1.1",
  "component": {
    "group": "org.junit.jupiter",
    "module": "junit-jupiter-api",
    "version": "5.6.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "6z5e52fxwrbhlhwdrxkyhcdiiu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.junit",
          "module": "junit-bom",
          "version": {
            "requires": "5.6.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.apiguardian",
          "module": "apiguardian-api",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.opentest4j",
          "module": "opentest4j",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-commons",
          "version": {
            "requires": "1.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "junit-jupiter-api-5.6.2.jar",
          "url": "junit-jupiter-api-5.6.2.jar",
          "size": 154036,
          "sha512": "8f05e1cd7abe6b7662dcf0136827fe1917b5d6716bc632399d1abaeca7d0afddc90766700faa39ecd1ce122586fb0e3a081a3acb3b5449c4bd4fe590c64d6905",
          "sha256": "3f476de9b214f20ca69da51e801186d001f67328a686df81bc3de3ba11953870",
          "sha1": "c9ba885abfe975cda123bf6f8f0a69a1b46956d0",
          "md5": "134c39075fcc504a722b1b33432a1111"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.junit",
          "module": "junit-bom",
          "version": {
            "requires": "5.6.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.apiguardian",
          "module": "apiguardian-api",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.opentest4j",
          "module": "opentest4j",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-commons",
          "version": {
            "requires": "1.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "junit-jupiter-api-5.6.2.jar",
          "url": "junit-jupiter-api-5.6.2.jar",
          "size": 154036,
          "sha512": "8f05e1cd7abe6b7662dcf0136827fe1917b5d6716bc632399d1abaeca7d0afddc90766700faa39ecd1ce122586fb0e3a081a3acb3b5449c4bd4fe590c64d6905",
          "sha256": "3f476de9b214f20ca69da51e801186d001f67328a686df81bc3de3ba11953870",
          "sha1": "c9ba885abfe975cda123bf6f8f0a69a1b46956d0",
          "md5": "134c39075fcc504a722b1b33432a1111"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "junit-jupiter-api-5.6.2-javadoc.jar",
          "url": "junit-jupiter-api-5.6.2-javadoc.jar",
          "size": 971092,
          "sha512": "84202812d4fb4ffdba90e112780a642b207be5ecbe1ec0ed8cabce4f441ebc4e2e7ce35e823c80153b415fa096b2c2dfabd5bed3a8c6a20c1c36f274a4ed4038",
          "sha256": "a7ca2400c6e9b0b0cd32115de599fbd9c4962e8d4982c383c4e22ac442b93524",
          "sha1": "6705f06ff57d78b1f2f938b9022042874ea73b63",
          "md5": "897e238b1f746fa8f9424acd2b214444"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "junit-jupiter-api-5.6.2-sources.jar",
          "url": "junit-jupiter-api-5.6.2-sources.jar",
          "size": 161197,
          "sha512": "cfa10341a1be531ecc1cf064a179fe70b56e05812e3f5547e376ae8f8d53bdbab21ce3089e99c184421cbf817573935e36efeaeea6a4daa129583db20f7fe583",
          "sha256": "da4cd6e4ca39af9f45c6dbb006db6df492210c415bd017ad3fe484a485cf65e7",
          "sha1": "ce1129e07053701f7458120b12229aedb05bcd4a",
          "md5": "7beb888afd49856d31b9980aa35613ec"
        }
      ]
    }
  ]
}
